version: "3"

services:
  database:
    container_name: blogs_api_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    build: .
    user: node
    volumes:
      - ./:/app
    container_name: blogs_api
    restart: always
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
      JWT_SECRET: secretJWT
